name = "QCMaterial"
uuid = "a9cd9503-f9e9-42c1-955f-178e1ea1d76e"
authors = ["Hiroshi Shinaoka <h.shinaoka@gmail.com> and contributors"]
version = "0.1.0"

[deps]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
MPI = "da04e1cc-30fd-572f-bb4f-1f8673147195"
PyCall = "438e738f-606a-5dbb-bf0a-cddfbfd45ab0"

[compat]
MPI = "0.17"
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
